---
title: "Report 10-7"
author: "Mao Hu"
date: "Monday, October 06, 2014"
output: html_document
---

Load scripts:

```{r}
setwd("~/GitHub/affectControlTheory/simulation/Report 10-7")
source("runSimulation.R")
```


Simulate in-context evaluation of actor, only main effects, with 2-way interactions, and with three-way interactions.
```{r} 
#Model coefficients
#coefficients taken from Lynn's book
simulation.model.eae.main = c("intercept" = -0.098, 
          "ae" = 0.47, 
          "ap" = 0, 
          "aa" = 0, 
          "be" = 0.425, 
          "bp" = -0.069, 
          "ba" = -0.106, 
          "oe" = 0.055, 
          "op" = 0,
          "oa" = 0, 
          "ae.be" = 0,
          "ae.bp" = 0,
          "ae.ba" = 0,
          "ae.oe" = 0, 
          "ae.op" = 0, 
          "ae.oa" = 0, 
          "ap.be" = 0, 
          "ap.bp" = 0, 
          "ap.ba" = 0, 
          "ap.oe" = 0, 
          "ap.op" = 0, 
          "ap.oa" = 0, 
          "aa.be" = 0, 
          "aa.bp" = 0, 
          "aa.ba" = 0 , 
          "aa.oe" = 0, 
          "aa.op" = 0, 
          "aa.oa" = 0, 
          "be.oe" = 0, 
          "be.op" = 0, 
          "be.oa" = 0, 
          "bp.oe" = 0, 
          "bp.op" = 0, 
          "bp.oa" = 0, 
          "ba.oe" = 0, 
          "ba.op" = 0, 
          "ba.oa" = 0, 
          "ae.be.oe" = 0, 
          "ae.be.op" = 0, 
          "ae.be.oa" = 0, 
          "ae.bp.oe" = 0, 
          "ae.bp.op" = 0, 
          "ae.bp.oa" = 0, 
          "ae.ba.oe" = 0, 
          "ae.ba.op" = 0, 
          "ae.ba.oa" = 0, 
          "ap.be.oe" = 0, 
          "ap.be.op" = 0, 
          "ap.be.oa" = 0, 
          "ap.bp.oe" = 0, 
          "ap.bp.op" = 0, 
          "ap.bp.oa" = 0, 
          "ap.ba.oe" = 0, 
          "ap.ba.op" = 0, 
          "ap.ba.oa" = 0, 
          "aa.be.oe" = 0, 
          "aa.be.op" = 0, 
          "aa.be.oa" = 0, 
          "aa.bp.oe" = 0, 
          "aa.bp.op" = 0, 
          "aa.bp.oa" = 0, 
          "aa.ba.oe" = 0, 
          "aa.ba.op" = 0, 
          "aa.ba.oa" = 0)

simulation.model.eae.2way = c("intercept" = -0.098, 
          "ae" = 0.47, 
          "ap" = 0, 
          "aa" = 0, 
          "be" = 0.425, 
          "bp" = -0.069, 
          "ba" = -0.106, 
          "oe" = 0.055, 
          "op" = 0,
          "oa" = 0, 
          "ae.be" = 0.048,
          "ae.bp" = -0.38,
          "ae.ba" = 0,
          "ae.oe" = 0, 
          "ae.op" = 0, 
          "ae.oa" = 0, 
          "ap.be" = 0, 
          "ap.bp" = 0, 
          "ap.ba" = 0, 
          "ap.oe" = 0, 
          "ap.op" = 0, 
          "ap.oa" = 0, 
          "aa.be" = 0, 
          "aa.bp" = 0, 
          "aa.ba" = 0 , 
          "aa.oe" = 0, 
          "aa.op" = 0, 
          "aa.oa" = 0, 
          "be.oe" = 0.130, 
          "be.op" = -0.058, 
          "be.oa" = 0, 
          "bp.oe" = -0.070, 
          "bp.op" = 0.068, 
          "bp.oa" = 0, 
          "ba.oe" = 0, 
          "ba.op" = 0, 
          "ba.oa" = 0, 
          "ae.be.oe" = 0, 
          "ae.be.op" = 0, 
          "ae.be.oa" = 0, 
          "ae.bp.oe" = 0, 
          "ae.bp.op" = 0, 
          "ae.bp.oa" = 0, 
          "ae.ba.oe" = 0, 
          "ae.ba.op" = 0, 
          "ae.ba.oa" = 0, 
          "ap.be.oe" = 0, 
          "ap.be.op" = 0, 
          "ap.be.oa" = 0, 
          "ap.bp.oe" = 0, 
          "ap.bp.op" = 0, 
          "ap.bp.oa" = 0, 
          "ap.ba.oe" = 0, 
          "ap.ba.op" = 0, 
          "ap.ba.oa" = 0, 
          "aa.be.oe" = 0, 
          "aa.be.op" = 0, 
          "aa.be.oa" = 0, 
          "aa.bp.oe" = 0, 
          "aa.bp.op" = 0, 
          "aa.bp.oa" = 0, 
          "aa.ba.oe" = 0, 
          "aa.ba.op" = 0, 
          "aa.ba.oa" = 0)


simulation.model.eae.3way = c("intercept" = -0.098, 
          "ae" = 0.47, 
          "ap" = 0, 
          "aa" = 0, 
          "be" = 0.425, 
          "bp" = -0.069, 
          "ba" = -0.106, 
          "oe" = 0.055, 
          "op" = 0,
          "oa" = 0, 
          "ae.be" = 0.048,
          "ae.bp" = -0.38,
          "ae.ba" = 0,
          "ae.oe" = 0, 
          "ae.op" = 0, 
          "ae.oa" = 0, 
          "ap.be" = 0, 
          "ap.bp" = 0, 
          "ap.ba" = 0, 
          "ap.oe" = 0, 
          "ap.op" = 0, 
          "ap.oa" = 0, 
          "aa.be" = 0, 
          "aa.bp" = 0, 
          "aa.ba" = 0 , 
          "aa.oe" = 0, 
          "aa.op" = 0, 
          "aa.oa" = 0, 
          "be.oe" = 0.130, 
          "be.op" = -0.058, 
          "be.oa" = 0, 
          "bp.oe" = -0.070, 
          "bp.op" = 0.068, 
          "bp.oa" = 0, 
          "ba.oe" = 0, 
          "ba.op" = 0, 
          "ba.oa" = 0, 
          "ae.be.oe" = 0.026, 
          "ae.be.op" = 0, 
          "ae.be.oa" = 0, 
          "ae.bp.oe" = 0, 
          "ae.bp.op" = 0.033, 
          "ae.bp.oa" = 0, 
          "ae.ba.oe" = 0, 
          "ae.ba.op" = 0, 
          "ae.ba.oa" = 0, 
          "ap.be.oe" = 0, 
          "ap.be.op" = 0, 
          "ap.be.oa" = 0, 
          "ap.bp.oe" = 0, 
          "ap.bp.op" = 0, 
          "ap.bp.oa" = 0, 
          "ap.ba.oe" = 0, 
          "ap.ba.op" = 0, 
          "ap.ba.oa" = 0, 
          "aa.be.oe" = 0, 
          "aa.be.op" = 0, 
          "aa.be.oa" = 0, 
          "aa.bp.oe" = 0, 
          "aa.bp.op" = 0, 
          "aa.bp.oa" = 0, 
          "aa.ba.oe" = 0, 
          "aa.ba.op" = 0, 
          "aa.ba.oa" = 0.031)


```

Simulate in-context evaluation of behavior, main, 2-way, and 3-way.
```{r}
#Model coefficients
#coefficients taken from Lynn's book
simulation.model.ebe.main = c("intercept" = -0.051, 
          "ae" = 0.071, 
          "ap" = 0, 
          "aa" = 0, 
          "be" = 0.571, 
          "bp" = -0.095, 
          "ba" = -0.116, 
          "oe" = 0.035, 
          "op" = 0,
          "oa" = 0, 
          "ae.be" = 0,
          "ae.bp" = 0,
          "ae.ba" = 0,
          "ae.oe" = 0, 
          "ae.op" = 0, 
          "ae.oa" = 0, 
          "ap.be" = 0, 
          "ap.bp" = 0, 
          "ap.ba" = 0, 
          "ap.oe" = 0, 
          "ap.op" = 0, 
          "ap.oa" = 0, 
          "aa.be" = 0, 
          "aa.bp" = 0, 
          "aa.ba" = 0 , 
          "aa.oe" = 0, 
          "aa.op" = 0, 
          "aa.oa" = 0, 
          "be.oe" = 0, 
          "be.op" = 0, 
          "be.oa" = 0, 
          "bp.oe" = 0, 
          "bp.op" = 0, 
          "bp.oa" = 0, 
          "ba.oe" = 0, 
          "ba.op" = 0, 
          "ba.oa" = 0, 
          "ae.be.oe" = 0, 
          "ae.be.op" = 0, 
          "ae.be.oa" = 0, 
          "ae.bp.oe" = 0, 
          "ae.bp.op" = 0, 
          "ae.bp.oa" = 0, 
          "ae.ba.oe" = 0, 
          "ae.ba.op" = 0, 
          "ae.ba.oa" = 0, 
          "ap.be.oe" = 0, 
          "ap.be.op" = 0, 
          "ap.be.oa" = 0, 
          "ap.bp.oe" = 0, 
          "ap.bp.op" = 0, 
          "ap.bp.oa" = 0, 
          "ap.ba.oe" = 0, 
          "ap.ba.op" = 0, 
          "ap.ba.oa" = 0, 
          "aa.be.oe" = 0, 
          "aa.be.op" = 0, 
          "aa.be.oa" = 0, 
          "aa.bp.oe" = 0, 
          "aa.bp.op" = 0, 
          "aa.bp.oa" = 0, 
          "aa.ba.oe" = 0, 
          "aa.ba.op" = 0, 
          "aa.ba.oa" = 0)

simulation.model.ebe.2way = c("intercept" = -0.051, 
          "ae" = 0.071, 
          "ap" = 0, 
          "aa" = 0, 
          "be" = 0.571, 
          "bp" = -0.095, 
          "ba" = -0.116, 
          "oe" = 0.035, 
          "op" = 0,
          "oa" = 0, 
          "ae.be" = 0.015,
          "ae.bp" = 0.025,
          "ae.ba" = 0,
          "ae.oe" = 0, 
          "ae.op" = 0, 
          "ae.oa" = 0, 
          "ap.be" = 0.021, 
          "ap.bp" = 0, 
          "ap.ba" = 0, 
          "ap.oe" = 0, 
          "ap.op" = 0, 
          "ap.oa" = 0, 
          "aa.be" = 0, 
          "aa.bp" = 0, 
          "aa.ba" = 0 , 
          "aa.oe" = 0, 
          "aa.op" = 0, 
          "aa.oa" = 0, 
          "be.oe" = 0.116, 
          "be.op" = -0.052, 
          "be.oa" = 0, 
          "bp.oe" = -0.034, 
          "bp.op" = 0.071, 
          "bp.oa" = 0, 
          "ba.oe" = 0, 
          "ba.op" = 0.036, 
          "ba.oa" = 0, 
          "ae.be.oe" = 0, 
          "ae.be.op" = 0, 
          "ae.be.oa" = 0, 
          "ae.bp.oe" = 0, 
          "ae.bp.op" = 0, 
          "ae.bp.oa" = 0, 
          "ae.ba.oe" = 0, 
          "ae.ba.op" = 0, 
          "ae.ba.oa" = 0, 
          "ap.be.oe" = 0, 
          "ap.be.op" = 0, 
          "ap.be.oa" = 0, 
          "ap.bp.oe" = 0, 
          "ap.bp.op" = 0, 
          "ap.bp.oa" = 0, 
          "ap.ba.oe" = 0, 
          "ap.ba.op" = 0, 
          "ap.ba.oa" = 0, 
          "aa.be.oe" = 0, 
          "aa.be.op" = 0, 
          "aa.be.oa" = 0, 
          "aa.bp.oe" = 0, 
          "aa.bp.op" = 0, 
          "aa.bp.oa" = 0, 
          "aa.ba.oe" = 0, 
          "aa.ba.op" = 0, 
          "aa.ba.oa" = 0)


simulation.model.ebe.3way = c("intercept" = -0.051, 
          "ae" = 0.071, 
          "ap" = 0, 
          "aa" = 0, 
          "be" = 0.571, 
          "bp" = -0.095, 
          "ba" = -0.116, 
          "oe" = 0.035, 
          "op" = 0,
          "oa" = 0, 
          "ae.be" = 0.015,
          "ae.bp" = 0.025,
          "ae.ba" = 0,
          "ae.oe" = 0, 
          "ae.op" = 0, 
          "ae.oa" = 0, 
          "ap.be" = 0.021, 
          "ap.bp" = 0, 
          "ap.ba" = 0, 
          "ap.oe" = 0, 
          "ap.op" = 0, 
          "ap.oa" = 0, 
          "aa.be" = 0, 
          "aa.bp" = 0, 
          "aa.ba" = 0 , 
          "aa.oe" = 0, 
          "aa.op" = 0, 
          "aa.oa" = 0, 
          "be.oe" = 0.116, 
          "be.op" = -0.052, 
          "be.oa" = 0, 
          "bp.oe" = -0.034, 
          "bp.op" = 0.071, 
          "bp.oa" = 0, 
          "ba.oe" = 0, 
          "ba.op" = 0.036, 
          "ba.oa" = 0, 
          "ae.be.oe" = 0.021, 
          "ae.be.op" = 0, 
          "ae.be.oa" = 0, 
          "ae.bp.oe" = 0, 
          "ae.bp.op" = 0.018, 
          "ae.bp.oa" = 0, 
          "ae.ba.oe" = 0, 
          "ae.ba.op" = 0, 
          "ae.ba.oa" = 0, 
          "ap.be.oe" = 0, 
          "ap.be.op" = 0, 
          "ap.be.oa" = 0, 
          "ap.bp.oe" = 0, 
          "ap.bp.op" = -0.031, 
          "ap.bp.oa" = 0, 
          "ap.ba.oe" = 0, 
          "ap.ba.op" = 0, 
          "ap.ba.oa" = 0, 
          "aa.be.oe" = 0, 
          "aa.be.op" = 0, 
          "aa.be.oa" = 0, 
          "aa.bp.oe" = 0, 
          "aa.bp.op" = 0, 
          "aa.bp.oa" = 0, 
          "aa.ba.oe" = 0, 
          "aa.ba.op" = 0, 
          "aa.ba.oa" = 0)


```

Simulate in-context evaluation of object, main, 2-way, and 3-way.

```{r}

#Model coefficients
#coefficients taken from Lynn's book
simulation.model.eoe.main = c("intercept" = 0.73, 
          "ae" = 0.022, 
          "ap" = 0, 
          "aa" = 0, 
          "be" = 0.123, 
          "bp" = -0.033, 
          "ba" = 0, 
          "oe" = 0.622, 
          "op" = 0,
          "oa" = 0, 
          "ae.be" = 0,
          "ae.bp" = 0,
          "ae.ba" = 0,
          "ae.oe" = 0, 
          "ae.op" = 0, 
          "ae.oa" = 0, 
          "ap.be" = 0, 
          "ap.bp" = 0, 
          "ap.ba" = 0, 
          "ap.oe" = 0, 
          "ap.op" = 0, 
          "ap.oa" = 0, 
          "aa.be" = 0, 
          "aa.bp" = 0, 
          "aa.ba" = 0 , 
          "aa.oe" = 0, 
          "aa.op" = 0, 
          "aa.oa" = 0, 
          "be.oe" = 0, 
          "be.op" = 0, 
          "be.oa" = 0, 
          "bp.oe" = 0, 
          "bp.op" = 0, 
          "bp.oa" = 0, 
          "ba.oe" = 0, 
          "ba.op" = 0, 
          "ba.oa" = 0, 
          "ae.be.oe" = 0, 
          "ae.be.op" = 0, 
          "ae.be.oa" = 0, 
          "ae.bp.oe" = 0, 
          "ae.bp.op" = 0, 
          "ae.bp.oa" = 0, 
          "ae.ba.oe" = 0, 
          "ae.ba.op" = 0, 
          "ae.ba.oa" = 0, 
          "ap.be.oe" = 0, 
          "ap.be.op" = 0, 
          "ap.be.oa" = 0, 
          "ap.bp.oe" = 0, 
          "ap.bp.op" = 0, 
          "ap.bp.oa" = 0, 
          "ap.ba.oe" = 0, 
          "ap.ba.op" = 0, 
          "ap.ba.oa" = 0, 
          "aa.be.oe" = 0, 
          "aa.be.op" = 0, 
          "aa.be.oa" = 0, 
          "aa.bp.oe" = 0, 
          "aa.bp.op" = 0, 
          "aa.bp.oa" = 0, 
          "aa.ba.oe" = 0, 
          "aa.ba.op" = 0, 
          "aa.ba.oa" = 0)

simulation.model.eoe.2way = c("intercept" = 0.73, 
          "ae" = 0.022, 
          "ap" = 0, 
          "aa" = 0, 
          "be" = 0.123, 
          "bp" = -0.033, 
          "ba" = 0, 
          "oe" = 0.622, 
          "op" = 0,
          "oa" = 0, 
          "ae.be" = 0.038,
          "ae.bp" = 0,
          "ae.ba" = 0,
          "ae.oe" = 0, 
          "ae.op" = 0, 
          "ae.oa" = 0, 
          "ap.be" = -0.019, 
          "ap.bp" = 0, 
          "ap.ba" = 0, 
          "ap.oe" = 0, 
          "ap.op" = 0, 
          "ap.oa" = 0, 
          "aa.be" = 0, 
          "aa.bp" = 0, 
          "aa.ba" = 0.025, 
          "aa.oe" = 0, 
          "aa.op" = 0, 
          "aa.oa" = 0, 
          "be.oe" = 0.044, 
          "be.op" = 0.014, 
          "be.oa" = 0, 
          "bp.oe" = -0.037, 
          "bp.op" = 0, 
          "bp.oa" = -0.034, 
          "ba.oe" = 0.014, 
          "ba.op" = 0.033, 
          "ba.oa" = 0, 
          "ae.be.oe" = 0, 
          "ae.be.op" = 0, 
          "ae.be.oa" = 0, 
          "ae.bp.oe" = 0, 
          "ae.bp.op" = 0, 
          "ae.bp.oa" = 0, 
          "ae.ba.oe" = 0, 
          "ae.ba.op" = 0, 
          "ae.ba.oa" = 0, 
          "ap.be.oe" = 0, 
          "ap.be.op" = 0, 
          "ap.be.oa" = 0, 
          "ap.bp.oe" = 0, 
          "ap.bp.op" = 0, 
          "ap.bp.oa" = 0, 
          "ap.ba.oe" = 0, 
          "ap.ba.op" = 0, 
          "ap.ba.oa" = 0, 
          "aa.be.oe" = 0, 
          "aa.be.op" = 0, 
          "aa.be.oa" = 0, 
          "aa.bp.oe" = 0, 
          "aa.bp.op" = 0, 
          "aa.bp.oa" = 0, 
          "aa.ba.oe" = 0, 
          "aa.ba.op" = 0, 
          "aa.ba.oa" = 0)


simulation.model.eoe.3way = c("intercept" = 0.73, 
          "ae" = 0.022, 
          "ap" = 0, 
          "aa" = 0, 
          "be" = 0.123, 
          "bp" = -0.033, 
          "ba" = 0, 
          "oe" = 0.622, 
          "op" = 0,
          "oa" = 0, 
          "ae.be" = 0.038,
          "ae.bp" = 0,
          "ae.ba" = 0,
          "ae.oe" = 0, 
          "ae.op" = 0, 
          "ae.oa" = 0, 
          "ap.be" = -0.019, 
          "ap.bp" = 0, 
          "ap.ba" = 0, 
          "ap.oe" = 0, 
          "ap.op" = 0, 
          "ap.oa" = 0, 
          "aa.be" = 0, 
          "aa.bp" = 0, 
          "aa.ba" = 0.025, 
          "aa.oe" = 0, 
          "aa.op" = 0, 
          "aa.oa" = 0, 
          "be.oe" = 0.044, 
          "be.op" = 0.014, 
          "be.oa" = 0, 
          "bp.oe" = -0.037, 
          "bp.op" = 0, 
          "bp.oa" = -0.034, 
          "ba.oe" = 0.014, 
          "ba.op" = 0.033, 
          "ba.oa" = 0, 
          "ae.be.oe" = 0.12, 
          "ae.be.op" = 0, 
          "ae.be.oa" = 0, 
          "ae.bp.oe" = 0, 
          "ae.bp.op" = 0, 
          "ae.bp.oa" = 0, 
          "ae.ba.oe" = 0, 
          "ae.ba.op" = 0, 
          "ae.ba.oa" = 0, 
          "ap.be.oe" = 0, 
          "ap.be.op" = 0, 
          "ap.be.oa" = 0, 
          "ap.bp.oe" = 0, 
          "ap.bp.op" = 0, 
          "ap.bp.oa" = 0, 
          "ap.ba.oe" = 0, 
          "ap.ba.op" = 0, 
          "ap.ba.oa" = 0, 
          "aa.be.oe" = 0, 
          "aa.be.op" = 0, 
          "aa.be.oa" = 0, 
          "aa.bp.oe" = 0, 
          "aa.bp.op" = 0, 
          "aa.bp.oa" = 0, 
          "aa.ba.oe" = 0, 
          "aa.ba.op" = 0, 
          "aa.ba.oa" = 0)


```

Run simulation:
```{r, echo=FALSE}
SIMULATIONS = 100;

resultsMatrix = as.data.frame(matrix(NA, SIMULATIONS, 16))
names(resultsMatrix) = c("stepwiseTruePositive", "stepwiseFalsePositive", "stepwiseFalseNegative", "stepwiseTrueNegative",
                         "anovaTruePositive", "anovaFalsePositive", "anovaFalseNegative", "anovaTrueNegative",
                         "bmaTruePositive", "bmaFalsePositive", "bmaFalseNegative", "bmaTrueNegative",
                         "bmsTruePositive", "bmsFalsePositive", "bmsFalseNegative", "bmsTrueNegative")
for (i in 1:SIMULATIONS){
  
  print(i);
  
  simulation <- runSimulation(simulation.model.eae.main, trainSize=200, testSize=200)
  simulationIdentified <- simulation$var.iden
  
  
  storeResults <- c(checker(simulationIdentified$stepwise, simulationIdentified$truth),checker(simulationIdentified$anova, simulationIdentified$truth),checker(simulationIdentified$bma, simulationIdentified$truth),checker(simulationIdentified$bms, simulationIdentified$truth))
  
  resultsMatrix[i,] <- storeResults

  
}

resultsMatrix
colMeans(resultsMatrix)[1:4]
colMeans(resultsMatrix)[5:8]
colMeans(resultsMatrix)[9:12]
colMeans(resultsMatrix)[13:16]

```


```{r, echo=FALSE}
require(ggplot2)
require(reshape2)
require(dplyr)

truePositive <- as.data.frame(cbind("stepwise" = resultsMatrix$stepwiseTruePositive, 
                                    "anova" = resultsMatrix$anovaTruePositive,
                                    "bma" = resultsMatrix$bmaTruePositive,
                                    "bms" = resultsMatrix$bmsTruePositive))
truePositive <- melt(truePositive)

plotData <- melt(resultsMatrix)

getMethod <- function(variableName){
  index = grep(substr(variableName,1,3),c("stepwise","anova","bma","bms"))
  return(c("stepwise","anova","bma","bms")[index])
}

getStat <- function(variableName){
  name = substr(variableName,3,nchar(as.character(variableName)))
  select = c(grepl("TruePositive", name), grepl("FalsePositive", name), grepl("FalseNegative", name), grepl("TrueNegative", name))
  return(c("TruePositive","FalsePositive","FalseNegative","TrueNegative")[select])
}

plotData <- plotData %>% mutate(method = sapply(plotData$variable, FUN = getMethod)) %>% mutate(statType = factor(sapply(plotData$variable, FUN = getStat)))

p <- ggplot(plotData, aes(x = value, color = factor(method))) + geom_histogram(aes(y=..density..),fill="white", binwidth=1) 
p + facet_grid(. ~ statType, scales = "free")

p <- ggplot(plotData, aes(x = value)) + geom_histogram(aes(y=..density..), color = "steelblue", fill="white", binwidth=1) 
p + facet_grid(method ~ statType, scales = "free")



summary(plotData$statType)







```




